### ISSUE TITLE
Not Working: (node:7292) UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by MAZETAM** [saurass/VampireWhatsApp-V2#1]
Terminal Output:
>  node index.js
Welcome To Vampire WhatsApp
VampireWhatsApp listening on port 3000

> DevTools listening on ws://127.0.0.1:64433/devtools/browser/15b844bb-454c-4d96-ba87-96849588c0b6
(node:7292) UnhandledPromiseRejectionWarning: JavascriptError: javascript error: Cannot read property 'call' of undefined
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17134 x86_64)
    at Object.checkLegacyResponse (D:\laragon\www\VWA-V2\node_modules\selenium-webdriver\lib\error.js:585:15)
    at parseHttpResponse (D:\laragon\www\VWA-V2\node_modules\selenium-webdriver\lib\http.js:533:13)
    at Executor.execute (D:\laragon\www\VWA-V2\node_modules\selenium-webdriver\lib\http.js:468:26)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:7292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

On Browser:
window.Store is not generated.

**Comment by saurass** [comment]
Thanks for raising issue @MAZETAM . Will get it donw ASAP : )

**Comment by saurass** [comment]
I guess this resolves the issue well @MAZETAM : )

**Comment by MAZETAM** [comment]
Hi @saurass ,

To display QR Code, change:
`if(document.getElementsByClassName('_1pw2F')[0]){`
to
`if(document.getElementsByClassName('_1lmAJ')[0]){`

Regards,
MAZETAM
